#!/usr/bin/env python

import requests
import yaml

if __name__ == '__main__':
    url = 'https://neic.no/api/1.0/people.json'
    response = requests.get(url)
    people = response.json()

    ff = open('people.yaml', 'w+')
    yamlData = {'persons': []}

    for person in people:
        entry = {
            'name': people[person]["name"],
            'url': people[person]["url"],
            'lat': 60.178511,
            'lon': 60.178511,
            'skills': ['python', 'pps', 'cmake']
        }
        yamlData['persons'].append(entry)

    yaml.dump(yamlData, ff, allow_unicode=True)

    ff.close()
